### ISSUE TITLE
Mattermost plugin does not work

### ISSUE THREAD

**Issue by desertanwar** [seansackowitz/mattermost-plugin-jitsi#13]
Hello Seansackowitz,
I have downloaded the plugin for Mattermost server running on Ubuntu 18.4 bionic. When i try to up i get the following error.

Mar 27 18:43:47 lab-mmost1 platform[1032]: {"level":"error","ts":1553712227.977395,"caller":"app/plugin.go:97","msg":"Unable to activate plugin","plugin_id":"jitsi","error":"unable to copy webapp bundle directory: jitsi: stat /opt/mattermost/client/plugins/jitsi/webapp: no such file or directory","errorVerbose":"stat /opt/mattermost/client/plugins/jitsi/webapp: no such file or directory\nunable to copy webapp bundle directory: jitsi\ngithub.com/mattermost/mattermost-server/plugin.(*Environment).Activate\n\t/go/src/github.com/mattermost/mattermost-server/plugin/environment.go:189\ngithub.com/mattermost/mattermost-server/app.(*App).SyncPluginsActiveState\n\t/go/src/github.com/mattermost/mattermost-server/app/plugin.go:95\ngithub.com/mattermost/mattermost-server/app.(*App).InitPlugins\n\t/go/src/github.com/mattermost/mattermost-server/app/plugin.go:182\ngithub.com/mattermost/mattermost-server/app.(*Server).RunOldAppInitalization\n\t/go/src/github.com/mattermost/mattermost-server/app/server_app_adapters.go:139\ngithub.com/mattermost/mattermost-server/app.NewServer\n\t/go/src/github.com/mattermost/mattermost-server/app/server.go:177\ngithub.com/mattermost/mattermost-server/cmd/mattermost/commands.runServer\n\t/go/src/github.com/mattermost/mattermost-server/cmd/mattermost/commands/server.go:64\ngithub.com/mattermost/mattermost-server/cmd/mattermost/commands.serverCmdF\n\t/go/src/github.com/mattermost/mattermost-server/cmd/mattermost/commands/server.go:50\ngithub.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).execute\n\t/go/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:762\ngithub.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).ExecuteC\n\t/go/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:852\ngithub.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).Execute\n\t/go/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:800\ngithub.com/mattermost/mattermost-server/cmd/mattermost/commands.Run\n\t/go/src/github.com/mattermost/mattermost-server/cmd/mattermost/commands/root.go:14\nmain.main\n\t/go/src/github.com/mattermost/mattermost-server/cmd/mattermost/main.go:30\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:201\nruntime.goexit\n\t/usr/local/go/src/run

Then i manually copied the plugin the tar file and then untar it to plugins directory and restarted the server i still see the same error. 

I have also local jitsi-meet server which is working if i go to url of jitsi. But intergration of Jitsi with mattermost does not seem to work at all.

Can you kind suggest and help me where am i going wrong with this.

Kind regards
Mohammad

**Comment by seansackowitz** [comment]
@desertanwar This should be resolved now, but I would appreciate if you could test it. I apologize for the delay in resolving this issue.
