### ISSUE TITLE
No icon to start Meeting

### ISSUE THREAD

**Issue by freifunk-bamberg** [seansackowitz/mattermost-plugin-jitsi#19]
I have installes the Plugin 1.2.0 over the Upload in Mattermost, activate this and configure the Server URL. 
but no Icon ist shown in Mattermost to start an meeting.

The same is with 1.1.0

What i make wrong?

**Comment by lkraav** [comment]
Same with today's 1.3.0 release.

Is this plugin only for privately hosted Jitsi server?

**Comment by seansackowitz** [comment]
No, I use it with the jitsi url of `https://meet.jit.si` What is the error log you are getting in the server logs? If there are none showing, then check your client logs in Google chrome by opening the developer console `F12` and looking for any errors there regarding loading the jitsi plugin.

**Comment by lkraav** [comment]
Aha, I wasn't aware it requires a browser plugin. Will test that next.

**Comment by seansackowitz** [comment]
There is no additional browser plugin required. Once you install this jitsi plugin, and configure and enable it on your Mattermost server, it will work for all Mattermost users. You should see a camera button in the top right of your mattermost window.
![image](https://user-images.githubusercontent.com/14167060/77571356-9cf13700-6ea3-11ea-993a-03f44adccba7.png)

**Comment by GabinhoJean** [comment]
Same issue.

I'm am using Mattermost 5.0.0 version inside a container with the docker image  mattermost/mattermost-prod-app:5.0.0

I tried the 1.2.0 and the 1.3.0 but I got no information in the server log and in the browser log.

the only way is that the plugin stays at this state.
![image](https://user-images.githubusercontent.com/38891996/77645854-c40f3d80-6f63-11ea-9102-89e0bdf9cd37.png)

any idea please?

**Comment by seansackowitz** [comment]
@GabinhoJean I think your issue is that you are running 21 versions behind, when plugins have undergone major changes in that nearly 2 years time. If you upgrade to a recent version of Mattermost and still have this problem, then please open a new issue.

If for some reason you absolutely cannot upgrade, then you should try version 0.2.0 of this plugin, as that is the latest version that supports Mattermost 5.0.0.

**Comment by GabinhoJean** [comment]
Sorry,
I updated Mattermost to the version 5.21.0 and it's working fine.
Thank you
