### ISSUE TITLE
Can someone please clarify deployment and configuration?

### ISSUE THREAD

**Issue by mikebakke** [seansackowitz/mattermost-plugin-jitsi#20]
Hi

I uploaded the latest tgz and configured to enable and set the Jitsi URL to be the same as my MM server. I did this because in the MM log I could see an error message for Jitsi when the URL was blank.

I can create a meeting in the chat but any attempt to join it opens a new window/instance and with the error message 

"Team Not Found
The team you're requesting is private or does not exist. Please contact your Administrator for an invitation."

As I created the meeting it's fair to say I am invited?

I have no doubt I'm doing something wrong but....

**Comment by seansackowitz** [comment]
Hey @mikebakke You should put in the url to a Jitsi server. For example, if you were to use the Jitsi server hosted by the Jitsi developers, you can set the url to `https://meet.jit.si`

**Comment by mikebakke** [comment]
Hi - thanks for responding. I misunderstood - I thought the plugin also contained a Jitsi server itself hence did not specify the URL initially, but the plugin would not start unless I added it.

I will try with the "meet.jit.si" and sse what happens

Rgds

**Comment by mikebakke** [comment]
Hi again

ok that worked thanks. I had hoped to be able to host the bridge myself so I guess I need to look wider.

Regards

Mike

**Comment by seansackowitz** [comment]
If you wish to host the Jitsi server yourself, I can recommend that you give their official docker compose project a try. https://github.com/jitsi/docker-jitsi-meet
