### ISSUE TITLE
Setup Troubles

### ISSUE THREAD

**Issue by dovestyle** [seansackowitz/mattermost-plugin-jitsi#3]
Hi there!

I think I'm doing something wrong. I've downloaded the release and uploaded it to Mattermost, but the plugin won't activate, telling me that the JitsiURL is not configured. The readme states that it has server & webapp, but I'm guessing maybe the server isn't the Jitsi server? Do I still need to setup a jitsi-meet server separately? If not, what do I set JitsiURL to?

Thanks,
Nick

**Comment by seansackowitz** [comment]
You can set up your own jisti-meet server if you wish to have an on premises server, but just ensure that you have plenty of resources to handle it, as it is a pretty heavy system when you get several users in a call with screen shares.

If you do not want to set up your own server, there is the example server that jitsi.org hosts, and the url for that is: https://meet.jit.si/

**Comment by dovestyle** [comment]
Hey Sean, thanks a bunch! That clears everything up! Just had to be sure.

I'll close this so your issue tracker is back to being nice & clean. Thanks again! :)
