### ISSUE TITLE
Please make it work on Mobile Apps

### ISSUE THREAD

**Issue by rbdevr** [seansackowitz/mattermost-plugin-jitsi#31]
This is a great plugin. I have my self hosted mattermost and jitsi and I'm pleased to finally see some integration. 

But most of the users, like myself, use mobile/desktop apps. Therefore we need this plugin working on them too.

Also the ability to open jitsi-meet mobile app by pressing the "go meeting" button in MM would be pretty neat.

Cheers,

**Comment by seansackowitz** [comment]
Hey, I do myself use both of the mobile apps, and do not have any issues with the meeting opening in Jitsi. You do need to make sure that you configure the Jitsi Meet app on your phone to open those links first however. As I don't know what type of phone you have, I would recommend asking for more details on how to change the default links that Jitsi Meet opens on their community forums if you have more questions. https://community.jitsi.org/

**Comment by rbdevr** [comment]
I use iOS.

"you configure the Jitsi Meet app on your phone" I don't think thats the case.

ask in their community forum is the best bet.

**Comment by seansackowitz** [comment]
Sorry, I don't have an iPhone, so I cannot help you with that. As for adding a "Start Meeting" button on mobile, that is not currently possible as per mattermost's plugin documentation. see: https://developers.mattermost.com/extend/plugins/mobile/
The way that Android handles opening the link, is that it automatically captures the URL, and if it matches a specific pattern, say `https://jitsi.example.com/*` it will open the url in the registered app for that url. I have no idea how iOS does this functionality.

**Comment by rbdevr** [comment]
Its possible with the app but the app needs to register he is working on a specific URL.

In regards to MM plugin I did create a post there. aits going to be a bummer if its really not possible since there are many devs asking for this feature for years now.

https://forum.mattermost.org/t/mm-plugins-available-on-mobile-apps/9563
