### ISSUE TITLE
Error : We could not start a meeting at this time.

### ISSUE THREAD

**Issue by gfriloux** [seansackowitz/mattermost-plugin-jitsi#6]
Hello,

I just installed version 1.0.0 on my mattermost version 5.2.1.
Clicking on the camera show the following error message : `We could not start a meeting at this time.`

On the mattermost system console, i can see the following logs : 
```
{"level":"error","ts":1537215738.2268791,"caller":"plugin/client_rpc.go:295","msg":"Plugin failed to ServeHTTP, RPC call failed","plugin_id":"jitsi","error":"connection is shut down"}
{"level":"error","ts":1537215743.2270253,"caller":"plugin/client_rpc.go:247","msg":"Plugin failed to ServeHTTP, muxBroker couldn't accept connection","plugin_id":"jitsi","serve_http_stream_id":12,"error":"timeout waiting for accept"}
{"level":"info","ts":1537215743.2271106,"caller":"http/server.go:1080","msg":"http: multiple response.WriteHeader calls","source":"httpserver"}
{"level":"error","ts":1537215743.2270546,"caller":"plugin/client_rpc.go:268","msg":"Plugin failed to ServeHTTP, muxBroker couldn't Accept request body connecion","plugin_id":"jitsi","error":"timeout waiting for accept"}
{"level":"info","ts":1537215743.2271378,"caller":"http/server.go:1080","msg":"http: multiple response.WriteHeader calls","source":"httpserver"}
```
Both jitsi-meet and mattermost runs from docker containers.

I don't know where to look to give you more informations.

**Comment by seansackowitz** [comment]
Hey @gfriloux the only reason that you should get that message is if the meeting URL is not set in the plugin options. If you do have it set, try disabling, and re-enabling the plugin. I will add in an OnConfigurationChange method to capture a url change in the next version.

Let me know how this goes for you!

**Comment by gfriloux** [comment]
Oh, that was easy.
I had the url set, but disabling/enabling the plugin made it work!

I could have find that myself if i did a little more tests.
Thanks for your amazingly fast answer!

**Comment by dpointk** [comment]
Thanks for this. I've also had this issue with Zoom plugin. All was set correctly but only after disabling, and re-enabling the plugin the configuration worked.
