### ISSUE TITLE
Clicking "Join Meeting" just opens another Mattermost window

### ISSUE THREAD

**Issue by philiplb** [seansackowitz/mattermost-plugin-jitsi#7]
Hi,
I just entered "meet.jit.si" as server and can start calls now. But when I click on the "Join Meeting" button, it opens a new browser window with the Mattermost instance again with the Jitsi-URL appended: https://mattermost.foo.bar/meet.jit.si/<generatedRoomName> instead of https://meet.jit.si/<generatedRoomName>
What could I do here? If I enter https://meet.jit.si as server, it doesn't work at all with this log message:

> 2018-09-18T11:28:43.736156Z app[...]: {"level":"error","ts":1537270123.7358959,"caller":"plugin/client_rpc.go:295","msg":"Plugin failed to ServeHTTP, RPC call failed","plugin_id":"jitsi","error":"connection is shut down"}

**Comment by seansackowitz** [comment]
Hey @philiplb the url should have https://meet.jit.si as the url, and there have been a few issues that I have been observing, related to the plugin crashing due to the way that golang is converting errors. This was causing a whole host of issues, and I have just released a new version that should fix most of them. Please let me know if this works for you!

**Comment by philiplb** [comment]
Hi, thank you for the very fast reaction. Unfortunately the new version of the plugin fails to start (Mattermost 5.3.0):

> 2018-09-18T13:53:59.256317Z app[...]: {"level":"error","ts":1537278839.2560217,"caller":"app/plugin.go:70","msg":"Unable to activate plugin","plugin_id":"jitsi","error":"unable to copy webapp bundle directory: jitsi: stat plugins/jitsi/static: no such file or directory","errorVerbose":"stat plugins/jitsi/static: no such file or directory\nunable to copy webapp bundle directory: jitsi\ngithub.com/mattermost/mattermost-server/plugin.(*Environment).Activate\n\t/home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/plugin/environment.go:183\ngithub.com/mattermost/mattermost-server/app.(*App).SyncPluginsActiveState\n\t/home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/app/plugin.go:68\ngithub.com/mattermost/mattermost-server/app.(*App).InitPlugins.func2\n\t/home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/app/plugin.go:141\ngithub.com/mattermost/mattermost-server/app.(*App).InvokeConfigListeners\n\t/home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/app/config.go:134\ngithub.com/mattermost/mattermost-server/app.(*App).UpdateConfig\n\t/home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/app/config.go:46\ngithub.com/mattermost/mattermost-server/app.(*App).EnablePlugin\n\t/home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/app/plugin.go:206\ngithub.com/mattermost/mattermost-server/api4.enablePlugin\n\t/home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/api4/plugin.go:183\ngithub.com/mattermost/mattermost-server/web.Handler.ServeHTTP\n\t/home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/web/handlers.go:131\ngithub.com/mattermost/mattermost-server/web.(*Handler).ServeHTTP\n\t<autogenerated>:1\ngithub.com/mattermost/mattermost-server/vendor/github.com/gorilla/mux.(*Router).ServeHTTP\n\t/home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/mux/mux.go:162\ngithub.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers.recoveryHandler.ServeHTTP\n\t/home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers/recovery.go:78\ngithub.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers.(*recoveryHandler).ServeHTTP\n\t<autogenerated>:1\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2694\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1830\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:2361"}

**Comment by seansackowitz** [comment]
I would love to know how I uploaded version 0.2.0 as the release, but I verified that I have uploaded the correct files this time. You should be able to download them again from release 1.0.1, and they should work correctly now.

**Comment by philiplb** [comment]
Works now like a charm, thank you very much!
